[package]
name = "chaosdanmutool"
version = "0.10.0"
description = "A tool for process/view Danmu on bilibili"
authors = ["Golden_Water"]
license = "AGPL-3.0-only"
repository = "https://github.com/BiliGoldenWater/ChaosDanmuTool.git"
default-run = "chaosdanmutool"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.2", features = [] }

[dependencies]
serde_json = "1.0.82"
serde = { version = "1.0.138", features = ["derive"] }
tauri = { version = "1.0.2", features = [] }
raw-window-handle = "0.4.3"
futures-util = "0.3.21"
tokio = "1.19.2"
tokio-tungstenite = { version = "0.17.1", features = ["native-tls"] }
url = "2.2.2"
ts-rs = "6.2.0"
# live template: tss
# |#[derive(ts_rs::TS)]
# |#[ts(export, export_to = "../src/share/type/rust/$PATH$")]
# |struct $NAME$ {
# |  $END$
# |}
#
# live template: atss
# |#[derive(ts_rs::TS)]
# |#[ts(export, export_to = "../src/share/type/rust/$PATH$")]

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.0"
objc = "0.2.7"
MacTypes-sys = "2.1.0"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true  # Automatically strip symbols from the binary.
